<div>
	<form action="index.php?page=addsubject" method="POST">
	<label for="title">Title Subject : </label><input type="text" id="title">
	<label for="author_id">Author id : </label><input type="text" id="author_id">
	<label for="category_id">Number Category : </label><input type="text" id="category_id">
	<button type="submit">Valider</button>
	</form>
</div>
<div>
	<h3><a href="index.php?page=home">Retour </a></h3>
</div>