<div class="row">
	<div class="col-md-5">
		<form action="" method="post" class="subject_form"><?=$addSupSubject;?></form><a href="index.php?page=subject&id=<?=$Subject->getId();?>"><strong><?=$Subject->getTitle();?></strong></a>
	</div>
	<div class="col-md-2">
		<i><?=$Subject->getAuthor()->getName();?></i>
	</div>
	<div class="col-md-2">
		<p><?=$Subject->getCreation_date();?></p>
	</div>
	<div class="col-md-3">
		<i><?=$lastAuthor?></i>
	</div>

</div>

