
<div class="row new_subject">
	<div class="col-md-5">
		<a href="index.php?page=bloc_subject&id=<?=$Subject->getId()?>"><strong><?=$Subject->getTitle();?></strong></a>
	</div>
	<div class="col-md-2">
		<i><?=$Subject->getAuthor()->getName();?></i>
	</div>
	<div class="col-md-2">
		<p><?=$Subject->getCreation_date();?></p>
	</div>
	<div class="col-md-3">
		<i><?=$lastAuthor?></i>
	</div>
	<div class="subject">
		
	</div>

</div>

