<div class="search">
	<div class="container">
		
		<div class="col-md-3 pull-right">
			<form action="index.php?page=search" method="post">
				<div class="input-group">
					<input type="text" class="form-control" id="search" placeholder="Recherche" name="search">
					<span class="input-group-btn">
				        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
				     </span>
			   	</div>
			</form>
		</div>
	</div>
</div>