<div class="login">
	<div class="col-md-5 block">
		<fieldset>
			<legend>Connexion</legend>
			<form action="index.php?page=login" method="post">
				<div class="form-group">
					<label for="name">Pseudo</label>
					<input type="text" class="form-control" name="name">
				</div>
				<div class="form-group">
					<label for="password">Mot de passe</label>
					<input type="password" class="form-control" name="password">
				</div>

				<button type="submit"><i class="fa fa-key"></i> Se connecter</button>
			</form>
		</fieldset>
	</div>
</div>