<div class="member">
	<div class="row">
		<fieldset><legend>Liste des membres</legend></fieldset>
	</div>
	<div class="row">
		<div class="col-md-12 block">
			<table class="table table-condensed">
				<thead>
					<tr>
						<th>#</th>
						<th>Pseudo</th>
						<th>Date d'inscription</th>
						<th>Level</th>
					</tr>
				</thead>
				<tbody>
					<?php require("app/aff_member.php"); ?>
				</tbody>
			</table>
		</div>
	</div>
</div>