<nav class="nav navbar-default navbar-fixed-top">
	<div class="container">
		<a class="navbar-brand" href="index.php?page=home"><i class="fa fa-comments-o"></i> Forum</a>
		<ul class="nav navbar-nav navbar-right">
			<li>
				<div class="img_profile">
					<img src="<?=$_SESSION['avatar']?>" alt="avatar" class="pull-right">
				</div>
			</li>
			<li>
				<a href="index.php?page=ucp_user">
					<?=$_SESSION['name'];?> <i class="fa fa-gears"></i>
				</a>
			</li>
			<li><a href="index.php?page=logout">Déconnexion</a></li>
		</ul>
	</div>
</nav>