<nav class="nav navbar-default navbar-fixed-top">
	<div class="container">
		<a class="navbar-brand" href="index.php?page=home"><i class="fa fa-comments-o"></i> Forum</a>
		<ul class="nav navbar-nav navbar-right">
			<li><a href="index.php?page=home">Accueil</a></li>
			<li><a href="index.php?page=register">Inscription</a></li>
			<li><a href="index.php?page=login">Connexion</a></li>
			<li>
				<a href="index.php?page=member">Membres</a>
			</li>
		</ul>
	</div>
</nav>