<nav class="nav navbar-default navbar-fixed-top">
	<div class="container">
		<a class="navbar-brand" href="index.php?page=home"><i class="fa fa-comments-o"></i> Forum</a>
		<ul class="nav navbar-nav navbar-right">
			<li>
				<div class="img_profile">
					<img src="<?=$_SESSION['avatar']?>" alt="avatar" class="pull-right">
				</div>
			</li>
			<li clas="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					<?=$_SESSION['name'];?> <span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="index.php?page=<?=$link;?>"><i class="fa fa-gears"></i> Panel</a></li>
					<li class="divider"></li>
		         	<li><a href="index.php?page=logout"><i class="fa fa-close"></i> Déconnexion</a></li>
		        </ul>
			</li>
		</ul>
	</div>
</nav>