<div class="row message_subject">
	<div class="col-md-12">
		<div class="col-md-1">
			<div class="thumbnail_avatar">
				<img src="<?=$avatar?>" alt="">
			</div>
		</div>
		<div class="col-md-10 message_content">
			<div class="row">
				<div class="col-md-12">
					<strong><?=$Message->getAuthor()->getName();?></strong> • <i><?=$Message->getCreation_date();?>	</i>
						<span class="spacer_toolbar"></span>
						<?=$addSupButton;?>
						<?=$addEditButton;?>
				</div>
			</div>
			<div class="spacer_message"></div>
			<div class="row">
				<div class="col-md-12">
					<?=$Message->getText();?>
				</div>
			</div>
		</div>
	</div>
</div>