<div class="register">
	<div class="col-md-5 block">
		<fieldset>
			<legend>Inscription</legend>
			<span class="alert-danger"><?=$error;?></span>
				<form action="index.php?page=register" method="post">
					<div class="form-group"><label for="name">Pseudo</label><input type="text" name="login" class="form-control"></div>
					<div class="form-group"><label for="email">Email</label><input type="email" name="email" class="form-control"></div>
					<div class="form-group"><label for="password">Mot de passe</label><input type="password" name="password" class="form-control"></div>
					<div class="form-group"><label for="password2">Confirmation du mot de passe</label><input type="password" name="password2" class="form-control"></div>

					<button type="submit"><i class="fa fa-key"></i> Je m'inscris !</button>
					<button type="reset" class="reset_button"><i class="fa fa-remove"></i> Effacer</button>
				</form>
		</fieldset>
	</div>

	<div class="col-md-offset-2 col-md-5 block">
		<fieldset>
			<legend>Conditions générales</legend>
			<div class="cgu">
				<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius voluptatem possimus, praesentium ducimus delectus sed voluptate ab, repellendus eaque quis consequuntur ad, quaerat maiores! Fugiat expedita quo dolore ipsa commodi.</div>
				<div>Tempora explicabo asperiores error quidem consequuntur qui non placeat eligendi sed natus nam quod aspernatur expedita sapiente dolores quia temporibus deserunt accusamus quo minima omnis quae ducimus, incidunt pariatur similique?</div>
				<div>Harum aliquid quis maxime beatae aperiam officia laboriosam, voluptatem labore voluptatum, suscipit perspiciatis maiores dolores, error fugit blanditiis illum itaque cupiditate libero recusandae similique eligendi dolorum aut asperiores sequi. Libero!</div>
				<div>Explicabo vel vero molestias recusandae reiciendis sunt, voluptates minima blanditiis aut, possimus dicta, quos impedit minus! Voluptatum rerum ipsum numquam eum aspernatur adipisci, voluptas officia deserunt maxime error nisi iste.</div>
				<div>Blanditiis atque eveniet, aliquam soluta iste ex quae nostrum. Aperiam libero, distinctio, cupiditate laborum quos, pariatur modi deserunt eligendi odio delectus eaque quaerat alias nisi veritatis. Sed dolore suscipit ea.</div>
				<div>Laborum cupiditate, eaque soluta neque tempora debitis! Sit libero dignissimos numquam, omnis facilis architecto vitae sapiente, minus sed tempora tempore reprehenderit necessitatibus iure, magni, incidunt qui? Cupiditate, aperiam a officia.</div>
				<div>Assumenda magnam quae molestias ipsum inventore minus officia, neque quod, aliquam quos excepturi. Expedita hic cupiditate id, quam eius eos. Necessitatibus odit ex rem hic sunt nemo totam, tempore error!</div>
				<div>Quis molestiae sapiente sit suscipit, a temporibus, excepturi omnis laudantium facere inventore. Nam provident ipsa rerum, officiis ratione itaque iure nisi porro, consectetur eaque dolore perspiciatis earum vel delectus nostrum.</div>
				<div>Id deserunt adipisci hic iure, alias error, necessitatibus quia laborum quod sint dolor asperiores dolorem ullam praesentium quaerat quos fuga in libero maiores reiciendis modi! Eligendi et exercitationem error, quo!</div>
				<div>Facilis odio illo similique! Quibusdam quis eum eius fugit eaque unde? Incidunt ad laboriosam enim odio iure maiores, rerum aut harum non dignissimos consequatur quisquam nobis distinctio sit tempora ex.</div>
				</div>
		</fieldset>
	</div>
</div>