<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Forum</title>
	<link rel="stylesheet" href="sources/css/bootstrap.min.css">
	<link rel="stylesheet" href="sources/css/stylesheet.css">
	<link rel="stylesheet" href="sources/css/font-awesome.min.css">
	<script src="sources/js/jquery.js"></script>
	<script src="sources/js/bootstrap.min.js"></script>
	<script src="sources/js/realtime.js"></script>
	<script src="sources/js/jquery_ui_modif_min.js"></script>
	<script src="sources/js/script.js"></script>

</head>
<body>
	<div class="wrapper">
		<?php 
			require("app/menu.php");
			require("app/header.php");
			require("app/content.php");
			require("app/footer.php");
		 ?>
	 </div>
</body>
</html>