<div class="row">
	<h1>Vous êtes au sujet <?=$subject->getTitle();?> <i class="fa fa-comment"></i></h1>
	
	<div class="col-md-12 category_title">
		<a href=""><i class="fa fa-comment-o"></i> <?=$subject->getTitle();?></a>
	</div>
</div>

<div><?php require("app/message.php"); ?></div>

<form method="POST" action="">
	<div class="form-group">
		<label for="message">Répondre au sujet: </label>
		<textarea name="message" id="message" placeholder="Entrez votre message" cols="90" rows="4"></textarea>
	</div>
	
	<button>Envoyer</button>
</form>

<h3><a href="index.php?page=home">Retour </a></h3>