<div class="row">
	<h1>Vous êtes au sujet <?=$subject->getTitle();?> <i class="fa fa-comment"></i></h1>
	
	<div class="col-md-12 category_title">
		<a href=""><i class="fa fa-comment-o"></i> <?=$subject->getTitle();?></a>
	</div>
</div>

<div><?php require("app/message.php"); ?></div>

<div class="div_create"><button class="create_new_message">Répondre</button>

	<div class="new_message">
		<form method="POST" action="">
			<div class="form-group">
				<button class="pull-left hide_bloc">Cacher</button>
				<label for="message">Répondre au sujet: </label>
				<textarea class="form-control" rows="3" name="message" id="message"></textarea>
			</div>
			
			<button type="submit">Envoyer</button>
		</form>
	</div>
</div>
<h3><a href="index.php?page=home" class="return_home">◄ Retour </a></h3>