<div class="ucp_admin">
	<div class="row">
		<div class="col-md-5 block">
			<fieldset>
				<legend>Sélection de catégorie</legend>
				<span class="alert-danger"><!-- ----------------------------- INSERER VARIABLE ERREUR --></span>
				<form action="index.php?page=ucp_admin" method="post">
					<label for="category">Catégories</label>
					<select class="form-control" name="category" id="category" multiple>
						<?php require("app/admin_categorylist.php");?>
					</select>
					<button class="button_alert" type="submit" data-id="<?= $category->getId(); ?>"><i class="fa fa-remove"></i>  Supprimer</button>
				</form>
				<div class="alert alert-danger">
					<i class="fa fa-warning"></i> Avertissement ! Si une catégorie est supprimée, ses sujets seront transférés dans la catégorie "Archives". <br />(!) Bloquer avec Bootstrap la categorie "Archives".
				</div>
			</fieldset>
		</div>

		<div class="col-md-offset-2 col-md-5 block">
			<fieldset>
				<legend>Sélectionner la catégorie à modifier</legend>
					<span class="alert-warning"><?=$modif_category;?></span>
				<form action="index.php?page=ucp_admin" method="post">
					<div class="form-group">
						<label for="modif_category">Catégories</label>
						<select class="form-control" name="modif_category" id="modif_category" multiple>
							<?php require("app/admin_categorylist.php");?>
					</select>
					</div>
					<button class="button_success" type="submit"><i class="fa fa-check"></i>  Modifier</button>
				</form>
				<form action="index.php?page=ucp_admin" method="post">
					<div class="form-group">
						<label for="name">Nom</label>
						<input type="text" class="form-control" name="name_category" id="name" value="<?=$title;?>">
						<input name="id" type="hidden" value="<?=$id;?>">
					</div>
					<div class="form-group">
						<label for="pos">Position</label>
						<input type="number" class="form-control" name="pos_category" id="pos" value="<?=$position;?>">
					</div>
					<button class="button_success" type="submit"><i class="fa fa-check"></i>  Valider</button>
				</form>
			</fieldset>
		</div>
	</div>

	<div class="row">
		<div class="col-md-5 block block_mt">
			<fieldset>
				<legend>Gérer un utilisateur</legend>
				<span class="alert-danger"><!-- ----------------------------- INSERER VARIABLE ERREUR --></span>
				<form action="index.php?page=ucp_admin" method="post">
					<div class="form-group">
						<label for="searchName">Nom de l'utilisateur à modifier</label>
						<input type="text" name="searchName" id="searchName" class="form-control"/>
						<button class="button_success" type="submit"><i class="fa fa-check"></i> Valider</button>
						<hr>
					</div>
				</form>
			</fieldset>
		</div>
		<div class="col-md-offset-2 col-md-5 block block_mt">
			<fieldset>
				<legend>Suppression d'utilisateur</legend>
				<span class="alert-danger"><!-- ----------------------------- INSERER VARIABLE ERREUR --></span>
				<form action="index.php?page=ucp_admin" method="post">
					<div class="form-group">
						<label for="searchUser">Rechercher le membre</label>
						<input type="text" name="searchUser" id="searchUser" class="form-control">
					</div>
					<hr>
					<button class="button_alert" type="submit"><i class="fa fa-remove"></i> Supprimer</button>
				</form>
			</fieldset>
		</div>
	</div>
</div>