<div class="ucp">
	<fieldset>
		<legend>Modifier mon profil</legend>
	</fieldset>

	<div class="col-md-5 block">
		<h4>Avatar</h4>
		<div class="col-md-5">
			<a href="#" class="thumbnail">
	  			<img data-src="holder.js/100%x180" src="<?=$_SESSION['avatar'];?>" alt="avatar">
			</a>
		</div>
		<div class="col-md-7">
			<p><i>Mettez une url dans le champ afin de charger un avatar</i></p>
			<form action="index.php?page=ucp_user" method="post">
				<div class="input-group">
					<span class="input-group-btn">
				        <span class="btn btn-default"><i class="fa fa-area-chart"></i></span>
				     </span>
					<input type="text" class="form-control" id="av" placeholder="URL" name="avatar">
				</div>

				<button type="submit" class="pull-right"><i class="fa fa-photo"></i> Valider</button>
			</form>
		</div>
	</div>

	<div class="col-md-offset-2 col-md-5 block">
		<form action="index.php?page=ucp_user" method="post">
			<h4>Modifier mes informations</h4>
			<hr>
			<div class="form-group">
				<label for="name">Pseudo</label>
				<input type="text" class="form-control" name="name">
			</div>
			<div class="form-group">
				<label for="email">Email</label>
				<input type="email" class="form-control" name="email">
			</div>
			<div class="form-group">
				<label for="desc">Status</label>
				<textarea name="description" id="desc" cols="10" rows="2" class="form-control"></textarea>
			</div>

			<h4>Modifier mon mot de passe</h4>
			<hr>
			<div class="form-group">
				<label for="oldPassword">Ancien de mot de passe</label>
				<input type="password" class="form-control" name="password">
			</div>
			<div class="form-group">
				<label for="newPassword">Nouveau mot de passe</label>
				<input type="password" class="form-control" name="newPassword">
			</div>
			<div class="form-group">
				<label for="newPassword2">Confirmer mot de passe</label>
				<input type="password" class="form-control" name="newPassword">
			</div>

			<button type="submit"><i class="fa fa-edit"></i> Valider</button>
		</form>
	</div>
</div>