<div class="user">
	<div class="row">
		<div class="col-md-12">
			<fieldset><legend>Profil de <?=$user->getName();?></legend></fieldset>
		</div>
	</div>

	<div class="row">
		<div class="col-md-5 block user_profil">
			<fieldset><legend>Informations à propos de <?=$user->getName();?></legend></fieldset>
			<div class="col-md-4">
				<div href="#" class="thumbnail thumbnail_avatar">
		  			<img src="<?=$user->getAvatar()?>" alt="">
				</div>
			</div>
			<div class="col-md-7">
				<span><strong>Pseudo :</strong> <i><?=$user->getName();?></i></span>
				<span><strong>Level :</strong> <i><?=$user->getLevel();?></i></span>
				<span><strong>Date d'inscription :</strong> <i><?=$dateInscription;?></i></span>
				<span><strong>Description :</strong> <i><?=$user->getDescription();?></i></span>
			</div>		
		</div>
	</div>
</div>
